@host=http://localhost:5272
@adminPath=api/admin
@contentType=application/json

GET {{host}}/{{adminPath}}/users
content-type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NmY5YzcyNy1hNDFlLTRkNDctYTU4MC1mOGVhMmYzZDFjMGIiLCJpZCI6IjU2ZjljNzI3LWE0MWUtNGQ0Ny1hNTgwLWY4ZWEyZjNkMWMwYiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImdpdmVuX25hbWUiOiJBbiIsImZhbWlseV9uYW1lIjoiTWluaCIsInJvbGVzIjoiQWRtaW4iLCJwZXJtaXNzaW9ucyI6IltdIiwianRpIjoiNWFlZmMzZTAtZjljYS00ZTQzLWIxNjgtZjlhOTllNDRmNzUxIiwiZXhwIjoxNzEwNzI0NzI1LCJpc3MiOiJTZXJ2ZXIiLCJhdWQiOiJTZXJ2ZXIifQ.ygeD1oA3AJTTofy4w4rWZDBRfVjsxFhbUMsIjh9X4II