@host=http://localhost:5272
@adminPath=auth
@contentType=application/json

### Admin Account :
Post {{host}}/{{adminPath}}/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "admin@gmail.com",
    "password": "Admin123@"
}



### Student Account :

Post {{host}}/{{adminPath}}/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "student@gmail.com",
    "password": "Admin123@"
}

### Coordinator Account :

Post {{host}}/{{adminPath}}/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "nguyenvu260703.dev@gmail.com",
    "password": "Admin123@"
}

### Coordinator Account :

Post {{host}}/{{adminPath}}/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "nguyenvu260703.dev@gmail.com",
    "password": "Admin123@"
}
### Guest Account :

Post {{host}}/{{adminPath}}/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "guest@gmail.com",
    "password": "Admin123@"
}


